#框架路径配置
venom: {
      FRAMEWORK_ROOT: &root_path G:\\git_python\\venmon, #venom根目录，只需修改这里即可
      JSON_PATH: !splicing [*root_path,/temp_json],
      CONFIG_PATH: !splicing [*root_path,/temp_csv],
      CASE_ROOT: !splicing [*root_path,/config_case],
      PROJECT: {
         war: &war war,
         mars: &mars mars,
         odin: &odin odin
      },
      CENTER_TOKEN: &center_token 0bfca36866e72940a0f6cba4c9b91b9a5d9a69d6bb49de19abf4e8a2d0434147
}

#项目配置
#英雄无敌-国内
war: {
       PROJECT_NAME: *war,#项目代号
       SVN_INFO: "svn://new.svn.playcrab-inc.com/war/svn",#svn根路径地址
       CASE: *war, #case文件夹
       CSV_SPECIAL: "GB18030",#war特殊，导表编码
       CONFIG_SPECIAL: "csv",#svn后缀文件夹
       DING_TOKEN: [
         *center_token, #测试中心
         "ac9d671d9c281f4c2baaabd2d49edd4a22a2d68c022e2a2b37956f96bf2b8261"
       ],
}

#项目配置
#英雄无敌-欧美
mars: {
      PROJECT_NAME: *mars,
      SVN_INFO: "svn://new.svn.playcrab-inc.com/war-europe/svn",
      CASE: *mars,
      CSV_SPECIAL: "utf-8",
      CONFIG_SPECIAL: "csv",#svn后缀文件夹,
      DING_TOKEN: [
        *center_token, #测试中心
        "ac9d671d9c281f4c2baaabd2d49edd4a22a2d68c022e2a2b37956f96bf2b8261"
      ],
}

odin: {
       PROJECT_NAME: *odin,#项目代号
#       SVN_INFO: "svn://new.svn.playcrab-inc.com/war/svn",
       CASE: *odin,
       DING_TOKEN: [
        *center_token, #测试中心
        "b10e9bf8d9aa33d82b7ffa3fe898f38c59b9c294936e982d197d87386c71bd9a"
      ],
}
